apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-logger
  template:
    metadata:
      labels:
        app: simple-logger
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: python-logger
          image: simple-logger:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: simple-logger-service
spec:
  selector:
    app: simple-logger
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001